//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureTravelsVer1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public string UserId { get; set; }
        public int FlightId { get; set; }
        public int NumberOfAdults { get; set; }
        public int NumberOfKids { get; set; }
        public int BookingAmount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
