//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureTravelsVer1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rating
    {
        public int RatingId { get; set; }
        [Required(ErrorMessage = "Please enter a Rating, it cannot be left empty")]
        [Range(0, 10, ErrorMessage = "The score must be between 0 and 10")]
        public int RatingScore { get; set; }

        [Display(Name = "Email address")]
        [Required(ErrorMessage = "Please enter an email address.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string userEmail { get; set; }

        [Required(ErrorMessage = "Please enter a Feedback, it cannot be left empty")]
        public string Feedback { get; set; }
    }
}
